### ISSUE TITLE
Errors in search results and document processing of Kenya Gazette  in Gazeti.Africa

### ISSUE THREAD

**Issue by tlongers** [gazeti/aleph#3]
Thank you so much for putting together the amazing Gazeti.Africa service. it has been extremely useful to [our work](https://whowasincommand.com) so far, and I hope to continue using it in our research.  I have experienced some errors, however, which I hope are quick fixes! (cc @pudo just in case)

## 1. Where is the error?

Search without terms and filter for the `Kenya Gazette` collection:

https://gazeti.africa/documents?q=&offset=0&filter:collection_id=1&sort=newest

## 2. What is the error?

I'm seeing errors in the search listings where the document teaser/preview text should be:

Error 1:

`HTTPConnectionPool(host='tika', port=9998): Max retries exceeded with url: /tika (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc290527310>: Failed to establish a new connection: [Errno 111] Connection refused',))`

Error 2:

`[Errno 12] Cannot allocate memory`

<img width="828" alt="screen shot 2018-02-07 at 10 05 45" src="https://user-images.githubusercontent.com/2115933/35910455-800ebf28-0bee-11e8-8850-7e7e4c3120fa.png">

## 3. What did I expect to happen?

A complete search result would look like this:

<img width="651" alt="screen shot 2018-02-07 at 10 09 09" src="https://user-images.githubusercontent.com/2115933/35910581-f8f8391e-0bee-11e8-8a9d-f92097dd5c48.png">

**Comment by tlongers** [comment]
Here's the full error reporting and traceback from one of the documents:

Source: https://gazeti.africa/documents/9488

Crawler ID: `aleph_ke_gazette_crawler.crawler.Crawler->KE_gazettes`
Crawler Run: `18f1eecd6ebc4be186702267789dd17c`
Foreign ID: `opengazettes-ke-vol-119-no-121-special-dated-22-August-2017`
Content Hash: `f356b0cb947278b2cfde3c1e9576fa907a903ec6`
Error message: `HTTPConnectionPool(host='tika', port=9998): Max retries exceeded with url: /tika (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0cf342b190>: Failed to establish a new connection: [Errno 111] Connection refused',))`

Traceback:

>Traceback (most recent call last):
  File "/aleph/aleph/ingest/ingestor.py", line 122, in dispatch
    best_cls(collection_id).ingest(meta, local_path)
  File "/aleph/aleph/ingest/text.py", line 56, in ingest
    self.extract_pdf(meta, local_path)
  File "/aleph/aleph/ingest/text.py", line 30, in extract_pdf
    data = tika_pdf(pdf_path, languages=meta.languages)
  File "/aleph/aleph/ingest/tika.py", line 11, in extract_pdf
    r = requests.put(tika_url, data=f, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='tika', port=9998): Max retries exceeded with url: /tika (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f0cf342b190>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by tlongers** [comment]
If this isn't going to get fixed, can someone just say so? Thanks.

**Comment by pudo** [comment]
I think it's an operational issue, so there's little I can do, I'm afraid :(

**Comment by tlongers** [comment]
Thanks @pudo :) 

Can any of the devs indicate whether Gazeti.Africa still a live project; or on hiatus?

**Comment by DavidLemayian** [comment]
:) Hey @tlongers and @pudo.

@tlongers gazeti.AFRICA is not a live project yet. Surprised you even found it.. Honoured by the work you're doing.

We'll be able to update you once we have the document issues sorted though. Won't be until end of March though.

**Comment by tlongers** [comment]
@DavidLemayian thanks so much for the reply, and the work you've done on this so far - it's both impressive and very useful. We want it now! :) Ping me if you need a tester.  I'd definitely appreciate an update on the document issue as time allows.
